version: '3.9'

services:
  db:
    image: mongo:6.0
    container_name: mongodb-api-tira-duvida-chatgpt-kenlo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 123456
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  # Node api service
  api:
    container_name: api-tira-duvida-chatgpt-kenlo
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    links:
      - db
    depends_on: 
      - db